services:
  - type: web
    name: audit-htmc
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps chromium
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /tmp/playwright